# Generated by Django 3.1.1 on 2020-09-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
